/* MASSENGER V3 · core/runtime.js — Runtime Config reader + Feature Access Gate
   แยกจาก app.js (Phase 3 safe modularization) · classic script · ต้องโหลดก่อน app.js
   ฟังก์ชันทั้งหมดเป็น global (function declaration) — app.js เรียกใช้ผ่าน global scope เดิม */
/* ===== MASSENGER V3 · Runtime Config reader (Phase 2.5) — additive · central access only ===== */
var _RC_DEFAULTS={ENVIRONMENT:"uat",READ_ONLY:true,KILL_SWITCH:false,KILL_REDIRECT_URL:"",DESKTOP_PAGE_SIZE:100,MOBILE_PAGE_SIZE:40,ADMIN_MOBILE_PAGE_SIZE:50,DATE_RANGE_MAX_ROWS_DESKTOP:1e4,DATE_RANGE_MAX_ROWS_MOBILE:3e3,APP_BUILD:"3.1.0",LOG_LEVEL:"info"};
var _FEAT_DEFAULTS={dashboard:true,export:true,users:true,documents:true,messenger:true};
function _rcRaw(){try{return(typeof window!=="undefined"&&window.RUNTIME_CONFIG)||{}}catch(_){return{}}}
function _rcFeatRaw(){try{return(typeof window!=="undefined"&&window.FEATURES)||{}}catch(_){return{}}}
function _rcIsUat(){try{return String((_rcRaw().ENVIRONMENT||_RC_DEFAULTS.ENVIRONMENT)).toLowerCase()==="uat"}catch(_){return true}}
function _rcWarn(m){try{if(_rcIsUat())console.warn("[RUNTIME_CONFIG] "+m)}catch(_){}}
function getRuntimeBoolean(key,def){if(def===undefined)def=_RC_DEFAULTS[key];if(def===undefined)def=false;var v=_rcRaw()[key];if(typeof v==="boolean")return v;if(v!==undefined)_rcWarn(key+" ควรเป็น boolean \u2014 \u0e43\u0e0a\u0e49 default("+def+")");return def}
function getRuntimeNumber(key,def){if(def===undefined)def=_RC_DEFAULTS[key];if(typeof def!=="number")def=0;var v=_rcRaw()[key];var n=typeof v==="number"?v:(typeof v==="string"&&v.trim()!==""&&isFinite(+v)?+v:NaN);if(isFinite(n)&&n>0)return Math.floor(n);if(v!==undefined)_rcWarn(key+" \u0e15\u0e49\u0e2d\u0e07\u0e40\u0e1b\u0e47\u0e19\u0e15\u0e31\u0e27\u0e40\u0e25\u0e02>0 \u2014 default("+def+")");return def}
function getBuildVersion(){try{var v=_rcRaw().APP_BUILD;if(typeof v==="string"&&v.trim()!=="")return v.trim()}catch(_){}return _RC_DEFAULTS.APP_BUILD}
function getRuntimeFeature(name){var v=_rcFeatRaw()[name];if(typeof v==="boolean")return v;var d=_FEAT_DEFAULTS[name];return d===undefined?true:d}
function _rcValidate(){try{getRuntimeBoolean("READ_ONLY",true);getRuntimeBoolean("KILL_SWITCH",false);getRuntimeNumber("DESKTOP_PAGE_SIZE",100);getRuntimeNumber("MOBILE_PAGE_SIZE",40)}catch(_){}}
function _rcShowKill(){try{if(typeof hideAppLoader==="function")hideAppLoader()}catch(_){}var url="";try{url=String(_rcRaw().KILL_REDIRECT_URL||"").trim()}catch(_){}var link=url?'<a href="'+url+'" style="display:inline-block;margin-top:18px;padding:12px 22px;border-radius:8px;background:#10B981;color:#fff;font-weight:700;text-decoration:none">\u0e44\u0e1b\u0e17\u0e35\u0e48\u0e23\u0e30\u0e1a\u0e1a Production</a>':"";if(document.getElementById("rc-kill-screen"))return;var host=document.createElement("div");host.id="rc-kill-screen";host.style.cssText="position:fixed;inset:0;z-index:99999;background:#0B1018;color:#E2E8F0;display:flex;align-items:center;justify-content:center;text-align:center;font-family:system-ui,-apple-system,sans-serif;padding:24px";host.innerHTML='<div style="max-width:440px"><div style="font-size:44px;margin-bottom:8px">\ud83d\udee0</div><h1 style="font-size:22px;font-weight:800;margin:0 0 10px">\u0e1b\u0e34\u0e14\u0e1b\u0e23\u0e31\u0e1a\u0e1b\u0e23\u0e38\u0e07\u0e0a\u0e31\u0e48\u0e27\u0e04\u0e23\u0e32\u0e27</h1><div style="color:#94A3B8;font-size:15px;line-height:1.6">MASSENGER V3 \u0e16\u0e39\u0e01\u0e1b\u0e34\u0e14\u0e43\u0e0a\u0e49\u0e07\u0e32\u0e19\u0e0a\u0e31\u0e48\u0e27\u0e04\u0e23\u0e32\u0e27 (KILL_SWITCH)</div>'+link+"</div>";document.body.appendChild(host)}
/* ===== end Runtime Config reader ===== */
/* ===== MASSENGER V3 · Feature Access Gate + Safe Landing (Phase 2.6/2.7) ===== */
function _featureForView(v){v=String(v||"");if(v==="graphs"||v==="dashboard"||v==="messengers"||v==="shipping")return "dashboard";if(v==="users")return "users";if(v.indexOf("doc-")===0)return "documents";return null;}
function _viewFeatureEnabled(v){var f=_featureForView(v);return f?getRuntimeFeature(f):true;}
function _safeLandingView(){try{var d=(typeof _defaultLandingView==="function")?_defaultLandingView():"wait";if(d&&_viewFeatureEnabled(d))return d;}catch(_){}try{var ship=(typeof _isShippingOnly==="function")&&_isShippingOnly();if(!ship&&_viewFeatureEnabled("wait"))return "wait";}catch(_){}try{if(getRuntimeFeature("dashboard")&&typeof canSeeAdminDashboard==="function"&&canSeeAdminDashboard())return "dashboard";}catch(_){}return "__feature_unavailable__";}
function _renderFeatureUnavailable(feat){try{var vr=document.getElementById("view-root");if(!vr)return;var fl=feat?" ("+((typeof esc==="function")?esc(feat):feat)+")":"";vr.innerHTML='<div class="topbar"><div><h1>\u0e1f\u0e35\u0e40\u0e08\u0e2d\u0e23\u0e4c\u0e16\u0e39\u0e01\u0e1b\u0e34\u0e14\u0e43\u0e0a\u0e49\u0e07\u0e32\u0e19</h1><p class="sub">\u0e42\u0e21\u0e14\u0e39\u0e25\u0e19\u0e35\u0e49\u0e16\u0e39\u0e01\u0e1b\u0e34\u0e14\u0e0a\u0e31\u0e48\u0e27\u0e04\u0e23\u0e32\u0e27 (Feature Flag)</p></div></div><div class="content"><div class="panel" style="padding:40px;text-align:center"><div style="font-size:42px;margin-bottom:10px">\ud83d\udd12</div><div style="font-size:16px;color:var(--muted)">\u0e1f\u0e35\u0e40\u0e08\u0e2d\u0e23\u0e4c'+fl+' \u0e44\u0e21\u0e48\u0e1e\u0e23\u0e49\u0e2d\u0e21\u0e43\u0e0a\u0e49\u0e07\u0e32\u0e19\u0e43\u0e19\u0e02\u0e13\u0e30\u0e19\u0e35\u0e49</div></div></div>';try{if(typeof refreshIconsIn==="function")refreshIconsIn(vr)}catch(_){}}catch(_){}}
/* ===== end Feature Access Gate ===== */
