(function(){"use strict";var S=window.NJHR&&NJHR.compat&&NJHR.compat.scope;if(!S)throw new Error("RUNTIME_NOT_READY");var sbToken=S.sbToken;var EMP_STATUS=[["ACTIVE","ปฏิบัติงาน"],["PROBATION","ทดลองงาน"],["SUSPENDED","พักงาน"],["RESIGNED","พ้นสภาพ"]];var EMP_STATUS_MAP={ACTIVE:"ปฏิบัติงาน",PROBATION:"ทดลองงาน",SUSPENDED:"พักงาน",RESIGNED:"พ้นสภาพ"};var EMP_TYPE_OPTS=["พนักงานประจำ","พนักงานไม่ประจำ","พนักงานรายวัน","พนักงานสัญญาจ้าง","พนักงานทดลองงาน"];function empNormType(v){var t=String(v==null?"":v).replace(/[\s\u00A0\u200B]+/g,"");if(!t)return"";for(var i=0;i<EMP_TYPE_OPTS.length;i++){if(EMP_TYPE_OPTS[i].replace(/\s+/g,"")===t)return EMP_TYPE_OPTS[i]}var u=t.toUpperCase().replace(/[-_.]/g,"");var alias={"ประจำ":"พนักงานประจำ","พนง.ประจำ":"พนักงานประจำ","พนงประจำ":"พนักงานประจำ",FULLTIME:"พนักงานประจำ",PERMANENT:"พนักงานประจำ",MONTHLY:"พนักงานประจำ","ไม่ประจำ":"พนักงานไม่ประจำ","พนงไม่ประจำ":"พนักงานไม่ประจำ",PARTTIME:"พนักงานไม่ประจำ",TEMPORARY:"พนักงานไม่ประจำ",TEMP:"พนักงานไม่ประจำ","รายวัน":"พนักงานรายวัน",DAILY:"พนักงานรายวัน","สัญญาจ้าง":"พนักงานสัญญาจ้าง",CONTRACT:"พนักงานสัญญาจ้าง","ทดลองงาน":"พนักงานทดลองงาน",PROBATION:"พนักงานทดลองงาน"};return alias[t]||alias[u]||""}/* ---------- [RUN-166] EMP_EXCEL_COLUMNS = Source of Truth ของ Excel พนักงาน ----------
   "ดาวน์โหลดเทมเพลต" = แบบมาตรฐาน · "Export Excel" = แบบมาตรฐานเดียวกัน + ข้อมูลจริง
   ทั้ง 3 ทางต้องอ้างอิงชุดนี้ชุดเดียว ไม่สร้าง Header/Column คนละชุดอีก
     ดาวน์โหลดเทมเพลต  views/employees/import.js  empTemplate()
     Export Excel      views/employees/export.js  empExport()
     นำเข้า Excel       views/employees/import.js  empImportForm()  (map ตามชื่อหัวข้อ)
   แก้หัวข้อ/ลำดับ/จำนวนคอลัมน์ ให้แก้ที่นี่ที่เดียว แล้วทั้ง 3 ทางเปลี่ยนตามพร้อมกัน
   อยู่ใน shared-emp-meta ซึ่งเป็น deps ของทั้ง employees-import และ employees-export อยู่แล้ว
   จึงไม่ต้องแก้ asset-manifest */
var EMP_EXCEL_COLUMNS=[["รหัสพนักงาน","emp_code"],["คำนำหน้า","prefix"],["ชื่อ","first_name"],["นามสกุล","last_name"],["ชื่อเล่น","nickname"],["เพศ","gender"],["วันเกิด","birth_date"],["เลขบัตรประชาชน","national_id"],["เบอร์โทร","phone"],["แผนก","department_name"],["ตำแหน่ง","position_name"],["วันที่เริ่มงาน","start_date"],["ประเภทพนักงาน","emp_type"],["เงินเดือนพื้นฐาน","base_salary"],["ค่าน้ำมัน","fuel_allow"],["ค่าโทรศัพท์","phone_allow"],["ค่าตำแหน่ง","position_allow"],["ธนาคาร","bank_name"],["สาขา","bank_branch"],["เลขที่บัญชี","bank_account"],["เวลาเข้างาน","work_start"],["เวลาเลิกงาน","work_end"],["ลาป่วย (วัน/ปี)","leave_sick"],["ลากิจ (วัน/ปี)","leave_personal"],["ลาพักร้อน (วัน/ปี)","leave_vacation"],["อีเมล","email"],["ที่อยู่","address"],["ระดับ","level"]];
var EMP_EXCEL_REQUIRED=["รหัสพนักงาน","ชื่อ","นามสกุล","วันที่เริ่มงาน"];
/* คอลัมน์ที่ต้องเป็น "ตัวเลข" ใน Excel — rptSheetXml เขียน <v> เมื่อ typeof === "number" */
var EMP_EXCEL_NUM_KEYS=["base_salary","position_allow","fuel_allow","phone_allow","leave_sick","leave_personal","leave_vacation"];
/* ชื่อ Sheet ต้องชุดเดียวกัน — Import อ่าน SheetNames[0] จึงมีได้ Sheet เดียวเท่านั้น */
var EMP_EXCEL_SHEET="เทมเพลตพนักงาน";
function empExcelHead(){return EMP_EXCEL_COLUMNS.map(function(x){return x[0]})}
/* ความกว้างคอลัมน์คำนวณจากชื่อหัวข้อ — สูตรเดียวกันจึงได้ค่าเท่ากันทุกคอลัมน์ */
function empExcelWidths(){return empExcelHead().map(function(h){return Math.min(Math.max(String(h).length+6,12),26)})}
/* Title 5 บรรทัดเสมอ -> Header อยู่แถว 6 และ rptSheetXml Freeze ที่ A7 เหมือนกันทั้งสองไฟล์
   4 บรรทัดแรกตรงกันเป๊ะ · บรรทัดที่ 5 เท่านั้นที่ต่างกันตามชนิดของไฟล์ */
function empExcelTitle(company,lastLine){return["เทมเพลตนำเข้าพนักงาน — "+company,"ช่องบังคับ: "+EMP_EXCEL_REQUIRED.join(" · "),"วันที่ต้องเป็นรูปแบบ YYYY-MM-DD เท่านั้น เช่น 2026-01-15","แผนกต้องตรงกับชื่อแผนกที่มีอยู่ในระบบ · สถานะ: ACTIVE / PROBATION / SUSPENDED / RESIGNED",String(lastLine==null?"":lastLine)]}
/* แปลง 1 แถวข้อมูลพนักงาน -> Array ตามลำดับคอลัมน์ของ EMP_EXCEL_COLUMNS
   กติกาค่าว่าง: ไม่มีข้อมูล = "" เท่านั้น · ห้าม undefined / null / [object Object]
   ตัวเลข = Number จริง · ที่เหลือ = ข้อความ (รักษาเลข 0 ด้านหน้าของรหัส/เลขบัญชี/เลขบัตร)
   วันที่ใช้ค่าดิบจาก RPC ซึ่งเป็น YYYY-MM-DD อยู่แล้ว — ห้ามแปลงเป็น พ.ศ. ไม่งั้น Import กลับไม่ได้ */
function empExcelRow(src){var o=src||{};return EMP_EXCEL_COLUMNS.map(function(c){var v=o[c[1]];if(v==null||v==="")return"";if(EMP_EXCEL_NUM_KEYS.indexOf(c[1])>=0){var n=Number(v);return isFinite(n)?n:""}if(typeof v==="object")return"";return String(v)})}
function ssoBindForm(){var on=document.getElementById("sso-f-on");var mode=document.getElementById("sso-f-mode");var wrap=document.getElementById("sso-f-wrap");var baseWrap=document.getElementById("sso-f-basewrap");var baseEl=document.getElementById("sso-f-base");var hint=document.getElementById("sso-f-hint");var eff=document.getElementById("sso-f-eff");var note=document.getElementById("sso-f-note");if(!on||!mode)return;function sync(){var enabled=on.checked;var manual=mode.value==="MANUAL";if(wrap)wrap.style.opacity=enabled?"":".5";mode.disabled=!enabled;if(eff)eff.disabled=!enabled;if(note)note.disabled=!enabled;if(baseWrap)baseWrap.style.display=enabled&&manual?"":"none";if(baseEl){baseEl.disabled=!(enabled&&manual);baseEl.required=enabled&&manual}if(hint){hint.textContent=!enabled?"พนักงานรายนี้ไม่เข้าประกันสังคม — ฐานและเงินสมทบเป็น 0.00":manual?"ใช้ฐานที่กำหนดเอง แล้วจำกัดด้วยฐานขั้นต่ำ–สูงสุดตามการตั้งค่าระบบ":"คำนวณอัตโนมัติจากรายการค่าจ้างที่ตั้งค่าไว้"}}on.onchange=sync;mode.onchange=sync;sync()}function ssoFormPayload(empId){var on=document.getElementById("sso-f-on");var mode=document.getElementById("sso-f-mode");var baseEl=document.getElementById("sso-f-base");var eff=document.getElementById("sso-f-eff");var note=document.getElementById("sso-f-note");var enabled=on?on.checked:true;var m=mode?mode.value:"AUTO";return{p_token:sbToken(),p_employee:empId,p_enabled:enabled,p_base_mode:m,p_custom_base:m==="MANUAL"&&baseEl&&baseEl.value!==""?Number(Number(baseEl.value).toFixed(2)):null,p_effective_date:eff&&eff.value?eff.value:null,p_note:note&&note.value.trim()?note.value.trim():null}}NJHR.compat.scope.EMP_EXCEL_COLUMNS=EMP_EXCEL_COLUMNS;NJHR.compat.scope.EMP_EXCEL_REQUIRED=EMP_EXCEL_REQUIRED;NJHR.compat.scope.EMP_EXCEL_NUM_KEYS=EMP_EXCEL_NUM_KEYS;NJHR.compat.scope.EMP_EXCEL_SHEET=EMP_EXCEL_SHEET;NJHR.compat.scope.empExcelHead=empExcelHead;NJHR.compat.scope.empExcelWidths=empExcelWidths;NJHR.compat.scope.empExcelTitle=empExcelTitle;NJHR.compat.scope.empExcelRow=empExcelRow;NJHR.compat.scope.EMP_STATUS=EMP_STATUS;NJHR.compat.scope.EMP_STATUS_MAP=EMP_STATUS_MAP;NJHR.compat.scope.EMP_TYPE_OPTS=EMP_TYPE_OPTS;NJHR.compat.scope.empNormType=empNormType;NJHR.compat.scope.ssoBindForm=ssoBindForm;NJHR.compat.scope.ssoFormPayload=ssoFormPayload})();
